### ISSUE TITLE
Nuevas columnas en libro ficsal de ventas y libro fiscal de compras

### ISSUE THREAD

**Issue by festovalros** [appits/rolda#2]
Al momento de imprimir el libro fiscal de ventas y compras se debe poder visualizar los campos siguientes al final del reporte actual:

1. % de retención
2. IVA percibido

![image](https://user-images.githubusercontent.com/902248/116725710-50cecb00-a9b0-11eb-83a2-5f69949c8069.png)

en el caso de compras seria 

1. % de retención
2. IVA Retenido a terceros

![image](https://user-images.githubusercontent.com/902248/116727668-dc495b80-a9b2-11eb-9752-928e6600aa6d.png)

**Comment by keiverobles** [comment]
Libro de Ventas
![image](https://user-images.githubusercontent.com/22960483/116790815-585fa400-aa84-11eb-8faf-b3fa88c3cc79.png)

Libro de Compras
![image](https://user-images.githubusercontent.com/22960483/116790807-51d12c80-aa84-11eb-85fb-167c44cca2e7.png)
