### ISSUE TITLE
Cambios en la ficha de partner

### ISSUE THREAD

**Issue by festovalros** [appits/rolda#3]
- [x] agregar campo zona de venta alfanumérico de por lo menos 150 caracteres.

![image](https://user-images.githubusercontent.com/902248/116729770-8fb34f80-a9b5-11eb-80fa-18aaff22798a.png)

- [x] agregar pestaña de otra información a res.partner con los siguientes campos:

- segmento campo de texto de 250 caracteres.
- Cod. Vendedor alfanumérico de 10 caracteres.
- Cod. Nielsen Numérico de dos digitos.
- Nielsen Alfanumérico de 100 caracteres.

![Untitled](https://user-images.githubusercontent.com/902248/116730698-cd64a800-a9b6-11eb-8e3e-4c1cef7d3603.png)

**Comment by keiverobles** [comment]
![image](https://user-images.githubusercontent.com/22960483/116791513-e63d8e00-aa88-11eb-808b-71c361427d4c.png)
