### ISSUE TITLE
Formato de reporte de factura

### ISSUE THREAD

**Issue by festovalros** [appits/rolda#4]
Adaptar el formato de reporte de factura al siguiente formato:

![image](https://user-images.githubusercontent.com/902248/116731960-6942e380-a9b8-11eb-9d9d-93863767a628.png)

- El campo zona de venta viene del partner que es el campo descrito en el issue #3 
- El total de unidades es el total de las cantidades de todas las lineas.
- El total kgrs el el total de kilos de las unidades de los productos  de todas las lineas a partit del campo weight de product.product, por ejemplo si un producto de la lineas de factura en el campo weight pone que pesa 2kg, y en la linea de factura hay 12 unidades entonces el total del peso sera 24 Kg esa misma operación sumada con todas las filas debe dar el total de Kgrs.
- las facturas deben poder aguantar al menos 40 lineas de productos entonces reducir el tamaño de la letra del reporte lo necesario para que pueda contener esa cantidad ya sea letra 10 o menos.
- al final como muestre el ejemplo agregar el monto del total de la factura en letras.

**Comment by keiverobles** [comment]
PDF de muestra para probar impresión sobre hoja prediseñada.
[Factura borrador.pdf](https://github.com/appits/rolda/files/6438051/Factura.borrador._.1.49.pdf)
